PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD /PWEAVER/SHIPURL-SYSTEMID .
    FIELD /PWEAVER/SHIPURL-PLANT .
    FIELD /PWEAVER/SHIPURL-CARRIERTYPE .
    FIELD /PWEAVER/SHIPURL-PWMODULE .
    FIELD /PWEAVER/SHIPURL-CCCATEGORY .
    FIELD /PWEAVER/SHIPURL-HOSTPORT .
    FIELD /PWEAVER/SHIPURL-TESTURL .
    FIELD /PWEAVER/SHIPURL-PRDURL .
    FIELD /PWEAVER/SHIPURL-PATHPREFIX .
    FIELD /PWEAVER/SHIPURL-NAMESPACE .
    FIELD /PWEAVER/SHIPURL-VERSION .
    FIELD /PWEAVER/SHIPURL-PROXYIP .
    FIELD /PWEAVER/SHIPURL-PROXYPORTNO .
    FIELD /PWEAVER/SHIPURL-DESCRIPTION .
    FIELD /PWEAVER/SHIPURL-URLSTRING .
    FIELD /PWEAVER/SHIPURL-SOAPACTION .
    FIELD /PWEAVER/SHIPURL-RFCDESTINATION .
    FIELD /PWEAVER/SHIPURL-FILENAME .
    FIELD /PWEAVER/SHIPURL-CONTENTTYPE .
    FIELD /PWEAVER/SHIPURL-PRINTMETHOD .
    FIELD /PWEAVER/SHIPURL-COMMUNICATION .
    FIELD /PWEAVER/SHIPURL-CARRIERMETHOD .
    FIELD /PWEAVER/SHIPURL-CARRIERIDF .
    FIELD /PWEAVER/SHIPURL-USERNAME .
    FIELD /PWEAVER/SHIPURL-PASSWORD .
    FIELD /PWEAVER/SHIPURL-CHILDKEY .
    FIELD /PWEAVER/SHIPURL-CHILDSECRET .
    FIELD /PWEAVER/SHIPURL-AUTHORIZATION_TYPE .
    FIELD /PWEAVER/SHIPURL-RESTMETHOD .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD /PWEAVER/SHIPURL-SYSTEMID .
    FIELD /PWEAVER/SHIPURL-PLANT .
    FIELD /PWEAVER/SHIPURL-CARRIERTYPE .
    FIELD /PWEAVER/SHIPURL-PWMODULE .
  module detail_pai.
 endchain.
